name: zapatos

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0-buster-slim
    timeout-minutes: 3

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run ESLint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
